using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
namespace DeidentifyLibrary {
    public partial class RandomData {
        private static List<string> _hospitalNames = new List<string>();

        private static void LoadHospitals() {
            _hospitalNames.Add("Childrens Mercey");
            _hospitalNames.Add("ACMH Hospital");
            _hospitalNames.Add("AHMC Anaheim Regional Medical Center");
            _hospitalNames.Add("AHS Southcrest Hospital, LLC dba Hillcrest Hospital South");
            _hospitalNames.Add("AMITA Health Adventist Medical Center Bolingbrook");
            _hospitalNames.Add("AMITA Health Adventist Medical Center GlenOaks");
            _hospitalNames.Add("AMITA Health Adventist Medical Center Hinsdale");
            _hospitalNames.Add("AMITA Health Adventist Medical Center La Grange");
            _hospitalNames.Add("AMITA Health Alexian Brothers Medical Center Elk Grove Village");
            _hospitalNames.Add("AMITA Health Mercy Medical Center Aurora");
            _hospitalNames.Add("AMITA Health Resurrection Medical Center Chicago");
            _hospitalNames.Add("AMITA Health Saint Francis Hospital Evanston");
            _hospitalNames.Add("AMITA Health Saint Joseph Hospital Chicago");
            _hospitalNames.Add("AMITA Health Saint Joseph Hospital Elgin");
            _hospitalNames.Add("AMITA Health Saint Joseph Medical Center Joliet");
            _hospitalNames.Add("AMITA Health Saints Mary and Elizabeth Medical Center Chicago");
            _hospitalNames.Add("AMITA Health St. Alexius Medical Center Hoffman Estates");
            _hospitalNames.Add("AMITA Health St. Mary's Hospital Kankakee");
            _hospitalNames.Add("Abbeville General Hospital");
            _hospitalNames.Add("Abbott Northwestern Hospital");
            _hospitalNames.Add("Abilene Regional Medical Center");
            _hospitalNames.Add("Abington Health Lansdale Hospital");
            _hospitalNames.Add("Abington Memorial Hospital");
            _hospitalNames.Add("Abrazo Arrowhead Campus");
            _hospitalNames.Add("Abrazo Central Campus");
            _hospitalNames.Add("Abrazo Scottsdale Campus");
            _hospitalNames.Add("Abrazo West Campus");
            _hospitalNames.Add("Acadia General Hospital (American Legion Hospital)");
            _hospitalNames.Add("Acadian Medical Center");
            _hospitalNames.Add("Addison Gilbert Hospital");
            _hospitalNames.Add("Adena Regional Medical Center");
            _hospitalNames.Add("Adirondack Medical Center - Saranac Lake");
            _hospitalNames.Add("AdventHealth Altamonte Springs");
            _hospitalNames.Add("AdventHealth Apopka");
            _hospitalNames.Add("AdventHealth Carrollwood");
            _hospitalNames.Add("AdventHealth Celebration");
            _hospitalNames.Add("AdventHealth Central Texas");
            _hospitalNames.Add("AdventHealth Dade City");
            _hospitalNames.Add("AdventHealth Daytona Beach");
            _hospitalNames.Add("AdventHealth DeLand");
            _hospitalNames.Add("AdventHealth East Orlando");
            _hospitalNames.Add("AdventHealth Fish Memorial");
            _hospitalNames.Add("AdventHealth Gordon");
            _hospitalNames.Add("AdventHealth Hendersonville");
            _hospitalNames.Add("AdventHealth Kissimmee");
            _hospitalNames.Add("AdventHealth Lake Placid");
            _hospitalNames.Add("AdventHealth Lake Wales");
            _hospitalNames.Add("AdventHealth New Smyrna Beach");
            _hospitalNames.Add("AdventHealth North Pinellas");
            _hospitalNames.Add("AdventHealth Ocala");
            _hospitalNames.Add("AdventHealth Orlando");
            _hospitalNames.Add("AdventHealth Ottawa");
            _hospitalNames.Add("AdventHealth Palm Coast");
            _hospitalNames.Add("AdventHealth Sebring");
            _hospitalNames.Add("AdventHealth Shawnee Mission");
            _hospitalNames.Add("AdventHealth Tampa");
            _hospitalNames.Add("AdventHealth Waterman");
            _hospitalNames.Add("AdventHealth Wesley Chapel");
            _hospitalNames.Add("AdventHealth Winter Park");
            _hospitalNames.Add("AdventHealth Zephyrhills");
            _hospitalNames.Add("Adventhealth Heart of Florida");
            _hospitalNames.Add("Adventist Health - Bakersfield");
            _hospitalNames.Add("Adventist Health Castle");
            _hospitalNames.Add("Adventist Health Glendale");
            _hospitalNames.Add("Adventist Health Lodi Memorial");
            _hospitalNames.Add("Adventist Health Portland Medical Center");
            _hospitalNames.Add("Adventist Health Simi Valley");
            _hospitalNames.Add("Adventist Health Sonora");
            _hospitalNames.Add("Adventist Health St. Helena");
            _hospitalNames.Add("Adventist Health Ukiah Valley");
            _hospitalNames.Add("Adventist Health White Memorial");
            _hospitalNames.Add("Adventist Health and Rideout");
            _hospitalNames.Add("Adventist HealthCare Fort Washington Medical Center");
            _hospitalNames.Add("Adventist HealthCare Shady Grove Medical Center");
            _hospitalNames.Add("Adventist HealthCare White Oak Medical Center");
            _hospitalNames.Add("Adventist Medical Center Hanford");
            _hospitalNames.Add("Adventist Medical Center Selma");
            _hospitalNames.Add("Advocate Christ Medical Center");
            _hospitalNames.Add("Advocate Condell Medical Center");
        }
    }
}
