using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
namespace DeidentifyLibrary
{
 public  partial class RandomData 
    {
        private static List<string> _randomWesternTexts = new List<string>();
        private static void LoadRandomWesternText() {
            _randomWesternTexts.Add("The town's sheriff, Marshal McAllister, had a drawl as slow as molasses and a temper as fiery as a branding iron.");
            _randomWesternTexts.Add("Miss Lulu Belle's saloon had a chandelier that sparkled like a desert diamond, and the dance floor was as smooth as a buttered biscuit.");
            _randomWesternTexts.Add("Two-Toed Pete had a limp as crooked as a rattlesnake's spine, but he could outdraw anyone in a game of poker.");
            _randomWesternTexts.Add("Out in the badlands, there were legends of a ghostly gunslinger, Phantom Pete, who could shoot the whiskers off a tumbleweed from a hundred paces.");
            _randomWesternTexts.Add("The town's preacher, Reverend Hickory, could quote the Good Book faster than a jackrabbit on a hot tin roof.");
            _randomWesternTexts.Add("Every summer, the town held a rodeo that was wilder than a bucking bronco and rowdier than a pack of coyotes.");
            _randomWesternTexts.Add("Dusty Gulch was a place where a man's word was as good as gold and a handshake was as binding as a contract.");
            _randomWesternTexts.Add("The local cafe, owned by Granny Smith, served up pies so delicious they could make a cowboy weep.");
            _randomWesternTexts.Add("Sheriff McCoy kept a picture of his sweetheart, Miss Ellie, tucked inside his hat, and he'd tip it to her every time he rode out on a mission.");
            _randomWesternTexts.Add("The prairie was vast and endless, stretching out to the horizon like a sea of golden wheat.");
            _randomWesternTexts.Add("The town's postman, Old Timer Joe, had been deliverin' mail for longer than anyone could remember, and he knew the secrets of every letter he carried.");
            _randomWesternTexts.Add("The local livery stable had more horses than a cavalry regiment and more hay than you could shake a stick at.");
            _randomWesternTexts.Add("Miss Kitty's saloon was a place where dreams were born and lost, where fortunes were won and squandered, and where the whiskey flowed like a mighty river.");
            _randomWesternTexts.Add("Outlaw Pete was rumored to have a hideout so well-hidden that even the birds couldn't find it.");
            _randomWesternTexts.Add("The town's blacksmith, Smithy McGraw, could shoe a horse faster than a jackrabbit could hop.");
            _randomWesternTexts.Add("Every year, Dusty Gulch hosted a chili cook-off that was hotter than a branding iron, and the competition was fiercer than a prairie fire.");
            _randomWesternTexts.Add("Old-timer Jedediah had a map to a secret gold mine, but he couldn't remember where he buried it.");
            _randomWesternTexts.Add("The town's barber, Whisker Willy, could give a shave so close it would make a rattlesnake's fangs jealous.");
            _randomWesternTexts.Add("Miss Lulu Belle's saloon had a mirror behind the bar that was said to be haunted by the ghost of a jilted lover.");
            _randomWesternTexts.Add("When the cattle drive came to town, the streets were as crowded as a beehive, and the cowboys were as rowdy as a pack of wild mustangs.");
            _randomWesternTexts.Add("The local sheriff's office had more wanted posters than wallpaper, and the list of outlaws was longer than a Texas summer.");
            _randomWesternTexts.Add("The town's doctor, Doc McScrubs, could stitch up a wound faster than a greased lightning bolt.");
            _randomWesternTexts.Add("Every Sunday, the church bells would ring out across the prairie, calling the faithful to worship.");
            _randomWesternTexts.Add("Miss Kitty's saloon had a stage where the best singers in the west would croon tunes that could make a cowboy's heart ache.");
            _randomWesternTexts.Add("The prairie was as wide as the sky, and the stars at night were as bright as a campfire.");
            _randomWesternTexts.Add("The town's schoolteacher, Miss Abigail, taught the young'uns to read, write, and wrangle cattle.");
            _randomWesternTexts.Add("Outlaw Pete was said to have a heart as cold as a winter storm and a six-shooter that never missed.");
            _randomWesternTexts.Add("The local bank, owned by Mr. Pennyworth, was the safest place in town, with a vault as thick as a fortress wall.");
            _randomWesternTexts.Add("Dusty Gulch had a rodeo clown named Crazy Clyde who could make even the toughest cowboys laugh.");
            _randomWesternTexts.Add("The town's mayor, Mayor McGillicuddy, had a beard as long as a riverboat, and he was known for his long-winded speeches.");
            _randomWesternTexts.Add("When the coyotes howled at night, it was said they were singin' the songs of the wild west.");
            _randomWesternTexts.Add("Miss Lulu Belle's saloon had a bartender named Slim who could mix a mean whiskey sour.");
            _randomWesternTexts.Add("The town's blacksmith, Blacksmith Billy, could forge a horseshoe faster than a prairie fire could spread.");
            _randomWesternTexts.Add("Outlaw Pete had a gang of varmints who would follow him anywhere, even into the depths of a rattlesnake's den.");
            _randomWesternTexts.Add("The local cafe, run by Granny Smith, served up biscuits so light they could float away on the wind.");
            _randomWesternTexts.Add("Dusty Gulch had a sheriff's badge that was as shiny as a silver dollar and as heavy as a guilty conscience.");
            _randomWesternTexts.Add("The prairie was dotted with cactus as far as the eye could see, each one as prickly as a porcupine.");
            _randomWesternTexts.Add("The town's preacher, Reverend Jeremiah, could preach a sermon that could make a cowboy repent.");
            _randomWesternTexts.Add("Two-Gun Tommy was known for his quick draw, but he was also known for his fondness for chewin' tobacco.");
            _randomWesternTexts.Add("Miss Kitty's saloon had a backroom where the poker games were hotter than a chili pepper.");
            _randomWesternTexts.Add("The local schoolteacher, Miss Abigail, had a ruler that could crack like a whip when she caught a student misbehaving.");
            _randomWesternTexts.Add("Dusty Gulch had a jailhouse with bars as thick as a bull's skull, and it was said that no one had ever escaped.");
            _randomWesternTexts.Add("The town's doctor, Doc McHealer, could cure ailments faster than a snakebite could kill.");
            _randomWesternTexts.Add("Outlaw Pete was said to have a hideout so well-hidden that even the stars couldn't find it.");
            _randomWesternTexts.Add("The local barber, Razor Rick, could give a haircut so close it could make a buffalo jealous.");
            _randomWesternTexts.Add("Miss Lulu Belle's saloon had a piano player named Ivory Joe who could play a tune that would make even the toughest cowboys cry.");
            _randomWesternTexts.Add("The town's mayor, Mayor McGonigal, was known for his elaborate speeches, but most folks couldn't understand a word he said.");
            _randomWesternTexts.Add("When the wind blew across the prairie, it carried the scent of sagebrush and adventure.");
            _randomWesternTexts.Add("Dusty Gulch had a rodeo clown named Laughin' Larry who could make even the cactus chuckle.");
            _randomWesternTexts.Add("The prairie was a vast expanse of beauty and danger, where the spirit of the wild west lived on in the hearts of its people.");
            _randomWesternTexts.Add("The sunsets in Dusty Gulch were like a fiery explosion in the sky, painting the desert with colors brighter than a prospector's dreams.");
            _randomWesternTexts.Add("When the wind whispered through the sagebrush, it carried secrets from the past, tales of lost gold mines, and the echoes of ghostly cowboys.");
            _randomWesternTexts.Add("Outlaw Pete was as slippery as a snake in a creek, and he had a hideout so hidden, even the coyotes couldn't find it.");
            _randomWesternTexts.Add("Miss Lulu Belle had a voice as sweet as honey and a laugh that could make a grizzly bear dance a jig.");
            _randomWesternTexts.Add("The local undertaker, Slim Pickens, had a smile that could freeze water faster than a blizzard in December.");
            _randomWesternTexts.Add("Every Saturday night, the town would gather at the local barn for a hoedown, where the fiddles played faster than a jackrabbit on roller skates.");
            _randomWesternTexts.Add("Old Bessie, the town's longhorn steer, was rumored to have once chased Black Bart clear across the prairie.");
            _randomWesternTexts.Add("The saloon's poker table was as worn as a cowboy's boots, and the chips were as plentiful as a herd of cattle.");
            _randomWesternTexts.Add("Dusty Gulch had its own set of rules, and the first one was, Don't mess with Texas.");
            _randomWesternTexts.Add("The sheriff's hat was as wide as a sombrero, and he wore it low over his eyes, like a gunslinger ready for a showdown.");
            _randomWesternTexts.Add("The local schoolteacher, Miss Abigail, was as strict as a schoolmarm should be, but she had a soft spot for apple pie.");
            _randomWesternTexts.Add("Old-timer Gus would sit on his porch, rockin' in his chair, and tell tales of the wild west that were taller than a saguaro cactus.");
            _randomWesternTexts.Add("When the stars came out, the desert night was as quiet as a church on a Monday mornin', and you could hear the coyotes singin' their lonesome songs.");
            _randomWesternTexts.Add("Two-Gun Tommy's boots were as shiny as a new penny, and his aim was as true as a North Star.");
            _randomWesternTexts.Add("The local doctor, Doc McStuffins, could patch up a bullet wound faster than a rattlesnake strike.");
            _randomWesternTexts.Add("Miss Kitty's piano player, Ivory Joe, could tickle the ivories faster than a jackrabbit hoppin' down a rabbit hole.");
            _randomWesternTexts.Add("The sheriff's horse, Thunder, was as loyal as a hound dog and as fast as a summer breeze.");
            _randomWesternTexts.Add("Out in the desert, the cacti stood tall and proud, like a regiment of soldiers guardin' the frontier.");
            _randomWesternTexts.Add("The town's livery stable was as busy as a beehive, with cowboys comin' and goin' like ants on a mission.");
            _randomWesternTexts.Add("When the rain finally came, it was a welcome relief, quenchin' the thirsty earth like a long drink of whiskey.");
            _randomWesternTexts.Add("The tumbleweeds were doin' the Texas two-step in the desert wind, and ol' Betsy the mule was singin' the blues like a lonesome coyote.");
            _randomWesternTexts.Add("Dusty Gulch was a town where the horses were faster than a lightning strike, and the poker games were wilder than a buckin' bronco at a rodeo.");
            _randomWesternTexts.Add("Sheriff McCoy had a mustache as thick as a buffalo's hide and a badge as shiny as a nugget of gold, and he wasn't afraid to use 'em.");
            _randomWesternTexts.Add("Miss Lizzie's pie was sweeter than a summer rain, and the cowboys would line up at her doorstep just to get a taste.");
            _randomWesternTexts.Add("Two-Gun Tommy was known for shootin' first and askin' questions later, but he had a soft spot for stray kittens and a mean poker face.");
            _randomWesternTexts.Add("The town's clock struck noon, and the whole place got quieter than a church mouse, 'cause everyone knew that meant it was time for a showdown.");
            _randomWesternTexts.Add("Blacksmith Jenkins could forge a horseshoe faster than a jackrabbit, and his anvil rang out like a church bell on Sunday mornin'.");
            _randomWesternTexts.Add("Out on the range, the cattle were lowin', and the cowboys were singin' cowboy songs that didn't make a lick of sense.");
            _randomWesternTexts.Add("Miss Kitty's parlor had more lace than a fancy lady's dress and more secrets than a coyote's den.");
            _randomWesternTexts.Add("The prairie was as wide as a Texas sky, and the stars were as numerous as the grains of sand, and it made a man feel smaller than a jackrabbit's footprint.");
            _randomWesternTexts.Add("As the tumbleweeds rolled through the dusty desert town, ol' Jeb grabbed his spurs and hollered, Yeehaw, varmints! It's high noon in the pickle barrel!");
            _randomWesternTexts.Add("The sun was hotter than a rattlesnake's kiss, and the only thing colder than a snake's heart was the sarsaparilla in Slim's saloon.");
            _randomWesternTexts.Add("Out on the prairie, Billy Bob was a-ridin' his trusty cactus, Betsy Lou, while his partner in crime, Two-Toed Pete, was busy rustlin' up some wild tumbleweed stew.");
            _randomWesternTexts.Add("Miss Lulu Belle, the belle of the ball, had hair as golden as a prospector's dream and a smile that could melt a sheriff's heart quicker than a stick of dynamite.");
            _randomWesternTexts.Add("The sheriff and his posse were hot on the trail of the ornery outlaw, Black Bart, who was known for robbin' stagecoaches and ticklin' tumbleweeds.");
            _randomWesternTexts.Add("The saloon piano was ticklin' the ivories like a sidewinder slitherin' through the sand, and the barkeep was pourin' shots of moonshine like it was goin' out of style.");
            _randomWesternTexts.Add("In the distance, the coyotes were a-howlin', and the night sky was as black as a bandit's heart, but that didn't stop ol' Doc Holliday from dealin' a winning hand of poker.");
            _randomWesternTexts.Add("Two cowpokes named Lefty and Righty were always arguin' about which way to turn when they reached the fork in the trail, and it usually ended in a showdown at high noon.");
            _randomWesternTexts.Add("Dust storms were as common as tumbleweeds, and folks had to tie their hats down tighter than a hog in a tornado to keep 'em from blowin' away.");
            _randomWesternTexts.Add("The town's blacksmith, Old Man Jenkins, had arms like tree trunks and a beard that could rival a grizzly's, but he had a heart as soft as a marshmallow in a campfire.");
            _randomWesternTexts.Add("When the sheriff heard tell of a gang of varmints causin' trouble down by the river, he saddled up his trusty steed, Thunder, and rode off into the sunset, ready for a showdown.");
            _randomWesternTexts.Add("Miss Kitty's saloon was the liveliest joint in town, with poker games goin' 'round the clock and cowboys dancin' the night away like a bunch of jackrabbits.");
            _randomWesternTexts.Add("Out in the mesquite, old-timer Jedediah was prospectin' for gold, and he swore he could hear the hills whisperin' secrets about buried treasure.");
            _randomWesternTexts.Add("The sheriff's badge shone like a lone star in the night, and he was always ready to uphold the law, even if it meant takin' on a gang of no-good varmints.");
            _randomWesternTexts.Add("The local preacher, Reverend McAllister, could quote scripture faster than a six-shooter, and he never missed a Sunday sermon, even if the pews were emptier than a desert highway.");
            _randomWesternTexts.Add("When the sun set over the horizon, and the stars came out to play, the town of Dusty Gulch came alive with the sounds of laughter, music, and the clinking of glasses.");
            _randomWesternTexts.Add("Old Bessie, the town's prized longhorn steer, was as ornery as a sidewinder with a toothache, but she was a legend in these parts, and folks came from miles around to catch a glimpse of her.");
            _randomWesternTexts.Add("The local barber, Sam the Scissorhand, could give a clean shave faster than a rattlesnake strike, and his shop was always buzzin' with talk of the latest shootouts and cattle drives.");
            _randomWesternTexts.Add("The mayor, Mayor McSnickerdoodle, was as crooked as a barrel of snakes, but the folks of Dusty Gulch didn't seem to mind as long as he kept the whiskey flowin' and the taxes low.");
            _randomWesternTexts.Add("When the full moon rose over the prairie, the ghost of the legendary gunslinger, Wild Bill Hickok, was said to ride through town, lookin' for one last showdown.");
        }
    }
}
